#!/bin/bash

# Compute the name of an assembly source file generated by one of the
# gen_asm_xxxx() functions below. The logic is the following:
# - if "$2" is not empty, output it directly
# - otherwise, change the file extension of $1 from .pl to .S and output
#   it.
# Usage: default_asm_file "$1" "$2"
#     or default_asm_file "$@"
#
# $1: generator path (perl script)
# $2: optional output file name.

PERL_EXE="perl -C0"

function default_asm_file () {
  if [ "$2" ]; then
    echo "$2"
  else
    echo "${1%%.pl}.S"
  fi
}

# Generate an ARM assembly file.
# $1: generator (perl script)
# $2: [optional] output file name
function gen_asm_arm () {
  local OUT
  OUT=$(default_asm_file "$@")
  $PERL_EXE "$1" void "$OUT" > "$OUT"
}

# Generate an ARMv8 64-bit assembly file.
# $1: generator (perl script)
# $2: [optional] output file name
function gen_asm_arm64 () {
  local OUT
  OUT=$(default_asm_file "$@")
  $PERL_EXE "$1" linux64 "$OUT" > "$OUT"
}

function gen_asm_mips () {
  local OUT
  OUT=$(default_asm_file "$@")
  # The perl scripts expect to run the target compiler as $CC to determine
  # the endianess of the target. Setting CC to true is a hack that forces the scripts
  # to generate little endian output
  CC=true $PERL_EXE "$1" o32 > "$OUT"
}

# TODO: gen_asm_mips64

# Print the values in a list with a prefix
# $1: prefix to use
# $2+: values of list
print_values_with_prefix() {
  declare -r prefix=$1
  shift
  for src; do
    echo -n " $prefix$src "
  done
}

function gen_asm_x86 () {
  local OUT
  OUT=$(default_asm_file "$@")
  $PERL_EXE "$1" elf -fPIC $(print_values_with_prefix -D $OPENSSL_CRYPTO_DEFINES_x86) > "$OUT"
}

function gen_asm_x86_64 () {
  local OUT
  OUT=$(default_asm_file "$@")
  $PERL_EXE "$1" elf "$OUT" > "$OUT"
}


# Generate arm asm
gen_asm_arm crypto/aes/asm/aes-armv4.pl
gen_asm_arm crypto/aes/asm/aesv8-armx.pl
gen_asm_arm crypto/aes/asm/bsaes-armv7.pl
gen_asm_arm crypto/bn/asm/armv4-gf2m.pl
gen_asm_arm crypto/bn/asm/armv4-mont.pl
gen_asm_arm crypto/modes/asm/ghash-armv4.pl
gen_asm_arm crypto/modes/asm/ghashv8-armx.pl
gen_asm_arm crypto/sha/asm/sha1-armv4-large.pl
gen_asm_arm crypto/sha/asm/sha256-armv4.pl
gen_asm_arm crypto/sha/asm/sha512-armv4.pl

# Generate armv8 asm
gen_asm_arm64 crypto/aes/asm/aesv8-armx.pl crypto/aes/asm/aesv8-armx-64.S
gen_asm_arm64 crypto/modes/asm/ghashv8-armx.pl crypto/modes/asm/ghashv8-armx-64.S
gen_asm_arm64 crypto/sha/asm/sha1-armv8.pl
gen_asm_arm64 crypto/sha/asm/sha512-armv8.pl crypto/sha/asm/sha256-armv8.S
gen_asm_arm64 crypto/sha/asm/sha512-armv8.pl

# Generate mips asm
gen_asm_mips crypto/aes/asm/aes-mips.pl
gen_asm_mips crypto/bn/asm/mips.pl crypto/bn/asm/bn-mips.S
gen_asm_mips crypto/bn/asm/mips-mont.pl
gen_asm_mips crypto/sha/asm/sha1-mips.pl
gen_asm_mips crypto/sha/asm/sha512-mips.pl crypto/sha/asm/sha256-mips.S

# TODO: Generate mips32r6 asm

# TODO: Generate mips64 asm

# Generate x86 asm
gen_asm_x86 crypto/x86cpuid.pl
gen_asm_x86 crypto/aes/asm/aes-586.pl
gen_asm_x86 crypto/aes/asm/vpaes-x86.pl
gen_asm_x86 crypto/aes/asm/aesni-x86.pl
gen_asm_x86 crypto/bn/asm/bn-586.pl
gen_asm_x86 crypto/bn/asm/co-586.pl
gen_asm_x86 crypto/bn/asm/x86-mont.pl
gen_asm_x86 crypto/bn/asm/x86-gf2m.pl
gen_asm_x86 crypto/modes/asm/ghash-x86.pl
gen_asm_x86 crypto/sha/asm/sha1-586.pl
gen_asm_x86 crypto/sha/asm/sha256-586.pl
gen_asm_x86 crypto/sha/asm/sha512-586.pl
gen_asm_x86 crypto/md5/asm/md5-586.pl
gen_asm_x86 crypto/des/asm/des-586.pl
gen_asm_x86 crypto/des/asm/crypt586.pl
gen_asm_x86 crypto/bf/asm/bf-586.pl
gen_asm_x86 crypto/ripemd/asm/rmd-586.pl
gen_asm_x86 crypto/camellia/asm/cmll-x86.pl
gen_asm_x86 crypto/cast/asm/cast-586.pl
gen_asm_x86 crypto/rc4/asm/rc4-586.pl 
gen_asm_x86 crypto/whrlpool/asm/wp-mmx.pl

# Generate x86_64 asm
gen_asm_x86_64 crypto/x86_64cpuid.pl
gen_asm_x86_64 crypto/sha/asm/sha1-x86_64.pl
gen_asm_x86_64 crypto/sha/asm/sha1-mb-x86_64.pl
gen_asm_x86_64 crypto/sha/asm/sha256-mb-x86_64.pl

gen_asm_x86_64 crypto/sha/asm/sha512-x86_64.pl crypto/sha/asm/sha256-x86_64.S
gen_asm_x86_64 crypto/sha/asm/sha512-x86_64.pl
gen_asm_x86_64 crypto/modes/asm/ghash-x86_64.pl
gen_asm_x86_64 crypto/modes/asm/aesni-gcm-x86_64.pl

gen_asm_x86_64 crypto/aes/asm/aesni-x86_64.pl
gen_asm_x86_64 crypto/aes/asm/vpaes-x86_64.pl
gen_asm_x86_64 crypto/aes/asm/bsaes-x86_64.pl
gen_asm_x86_64 crypto/aes/asm/aes-x86_64.pl
gen_asm_x86_64 crypto/aes/asm/aesni-sha1-x86_64.pl
gen_asm_x86_64 crypto/aes/asm/aesni-mb-x86_64.pl
gen_asm_x86_64 crypto/aes/asm/aesni-sha256-x86_64.pl
gen_asm_x86_64 crypto/aes/asm/aesni-x86_64.pl
gen_asm_x86_64 crypto/whrlpool/asm/wp-x86_64.pl

gen_asm_x86_64 crypto/md5/asm/md5-x86_64.pl
gen_asm_x86_64 crypto/bn/asm/x86_64-mont.pl
gen_asm_x86_64 crypto/bn/asm/x86_64-gf2m.pl
gen_asm_x86_64 crypto/bn/asm/x86_64-mont5.pl
gen_asm_x86_64 crypto/bn/asm/rsaz-x86_64.pl
gen_asm_x86_64 crypto/bn/asm/rsaz-avx2.pl
gen_asm_x86_64 crypto/ec/asm/ecp_nistz256-x86_64.pl
gen_asm_x86_64 crypto/rc4/asm/rc4-x86_64.pl
gen_asm_x86_64 crypto/rc4/asm/rc4-md5-x86_64.pl
gen_asm_x86_64 crypto/bn/asm/rsaz-avx2.pl
